sudo: required
language: csharp
solution: DotAdvancedDictionaryCore/DotAdvancedDictionaryCore.sln
mono: none
dist: trusty
script:
 - dotnet restore
 - dotnet test ./DotAdvancedDictionary.Test/DotAdvancedDictionary.Test.csproj -c Release
